### ISSUE TITLE
Consider Ed25519 batch verify

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#1104]
There exist numerical techniques for accelerating Ed25519 verify by batching multiple verify inputs.
Batch verify then indicates whether all signatures were valid or whether there was one invalid signature.

Previously, this technique was assumed to be too coarse. If an attacker sneaks a single invalid signature into the batch, he could invalidate all other validate signatures.

But batch verify is still useful in two cases:
1. Transactions with multiple signatures, which is becoming increasingly common
2. Batch verifying messages coming from the same peer. For many network protocols, participants in the peer-to-peer network are expected to only distribute messages with valid signatures. For example, sending invalid transactions via TPU/QUIC is considered a protocol violation that justifies connection termination anyways.

**Comment by ripatel-fd** [comment]
cc @0x0ece

**Comment by 0x0ece** [comment]
Batching doesn't work with strict_verify because of weird edge cases with torsion points. Closing this.
