### ISSUE TITLE
Switch usages of poll to ppoll

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#1177]
**Problem**

Our seccomp syscall filters don't build on Arm64, because we whitelist the poll syscall. However, arm64 only has ppoll.

This currently breaks the fddev/fdctl build on Arm64.

**Suggested Fix**

Option 1: More predictable syscalls

- Always call ppoll syscall, never call poll syscall
- Provide an `fd_poll` wrapper that provides the old poll API (as a drop in replacement), but issuing a ppoll syscall. This is what libc does on Arm64: https://elixir.bootlin.com/musl/v1.2.4/source/src/select/poll.c

Option 2: More flexible seccomp filters

- Allow conditionals in seccomp scripts that get translated down to C pre-processor `#if` switches

I think option 1 is more realistic/maintainable

**Comment by mmcgee-jump** [comment]
This should probably just use epoll

**Comment by ripatel-fd** [comment]
Closing this issue since the root cause is https://github.com/firedancer-io/firedancer/issues/1286
