### ISSUE TITLE
Add ASan support to fd_alloc

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#142]
**Problem**

ASan is unaware of the fd_alloc heap data structures and will fail to detect OOB heap accesses.
Heap unsoundness is a common source of bugs and security vulnerabilities.

**Feature Request**

Add ASan support to fd_alloc via the manual poisoning API. https://github.com/google/sanitizers/wiki/AddressSanitizerManualPoisoning

**Suggested Implementation**

- Poison everything (entire footprint of fd_alloc) on fd_alloc_join
- Whenever the allocator code accesses a superblock, temporarily unpoison it, and then poison it again before returning to the caller (so that invalid memory accesses to the superblock/metadata areas outside of the fd_alloc code are detected)
- Whenever an fd_alloc_malloc() call is made, unpoison the newly allocated user area
- Whenever an fd_alloc_free() call is made, poision the freed area
- Unpoison the entire footprint of fd_alloc on fd_alloc_leave

**Comment by ripatel-fd** [comment]
@ameya-deshmukh As discussed, assigning to you -- Thanks!

**Comment by ameya-deshmukh** [comment]
Thank you! Would love to work on this

**Comment by anoushk1234** [comment]
> Thank you! Would love to work on this

@ameya-deshmukh Is this implemented? Was going to take a look into it

**Comment by ameya-deshmukh** [comment]
@anoushk1234 yes, a part of it is. Its a WIP draft PR as of now, would be more than happy to collaborate on future work

**Comment by anoushk1234** [comment]
> @anoushk1234 yes, a part of it is. Its a WIP draft PR as of now, would be more than happy to collaborate on future work

Can you point me to the PR?

**Comment by ameya-deshmukh** [comment]
Sure. https://github.com/firedancer-io/firedancer/pull/214

**Comment by anoushk1234** [comment]
hey @ripatel-jump have created a PR, also had a few questions that I've dropped in the discord, would be great if you can answer them, thanks.

**Comment by ripatel-fd** [comment]
Duplicate of #40
