### ISSUE TITLE
util: provide rng on non-hosted

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#146]
//src/util/rng currently depends on `math.h`. 
This dependency should be removed as this library is not guaranteed to be bit-level identical between platforms.

rng depends on the following symbols:
- ldexp
- ldexpf
- log
- logf
- exp
- expf

(This is a non-trivial change)

**Comment by mmcgee-jump** [comment]
Not currently planned, will revisit as needed
