### ISSUE TITLE
util: add fd_cstr_ncasecmp

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#147]
//src/util/cstr provides `fd_cstr_casecmp` for case-insensitive C string compare.

Add a length bounded variant `fd_cstr_ncasecmp` like

```
int
fd_cstr_ncasecmp( char const * a,
                  char const * b,
                  ulong        sz )
```

Where `sz` is the max number of bytes `fd_cstr_ncasecmp` will read from either `a` or `b`.

Then fix usage at https://github.com/firedancer-io/firedancer/blob/a33d8e6e2c5fbe926090a856fc5fbfe41921c41f/src/util/pod/fd_pod.c#L345

**Comment by anoushk1234** [comment]
Hey @ripatel-jump can I take this up?

**Comment by ripatel-fd** [comment]
@anoushk1234 That'd be great -- thank you
