### ISSUE TITLE
Fix ShellCheck warnings

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#149]
The [ShellCheck](https://github.com/koalaman/shellcheck) tool has found a few code quality issues in the setup and test shell scripts.

Most of these warnings are about lack of quoting of variables. Should be easy to fix

**Example**

```
$ shellcheck ./src/app/frank/fd_frank_init

In ./src/app/frank/fd_frank_init line 41:
$BUILD/bin/fd_wksp_ctl delete $WKSP # Okay if fails ... might not exist already
^----^ SC2086: Double quote to prevent globbing and word splitting.
                              ^---^ SC2086: Double quote to prevent globbing and word splitting.
...
```

The above should be changed to

```
"$BUILD"/bin/fd_wksp_ctl delete "$WKSP"
```

**Comment by AlberErre** [comment]
Hey @ripatel-jump this looks like a good starting point to contribute, could you assign me the issue? 👀

**Comment by AlberErre** [comment]
@ripatel-jump I have created a PR handling these code quality issues on the shell scripts 🎉

Here is the PR -> https://github.com/firedancer-io/firedancer/pull/267
