### ISSUE TITLE
ballet: add ChaChaRng

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#151]
The Solana protocol uses a ChaCha20-based PRNG in various parts of the protocol (Gossip, Turbine, leader schedule).

Import a widely-used/battle-tested ChaCha20 C reference implementation to Firedancer. 

The OpenSSL implementation is probably the best option https://www.openssl.org/docs/man1.1.1/man3/EVP_chacha20_poly1305.html

Specifically, we need ChaCha20Core from rand_chacha: https://docs.rs/rand_chacha/latest/rand_chacha/struct.ChaCha20Core.html

**Comment by AlberErre** [comment]
I'm happy to pick this up @ripatel-jump 🚀 as discussed on #265

**Comment by AlberErre** [comment]
Hey @ripatel-jump I have created a PR implementing `ChaChaRng`, as well as unit tests 🎉

Here is the PR -> https://github.com/firedancer-io/firedancer/pull/324

Although, I have doubts regarding `Local.mk` file, as I don't have enough context regarding this building process.

**Comment by ripatel-fd** [comment]
Done in https://github.com/firedancer-io/firedancer/commit/bd8045fbeeb032cf9db4d5a17e571c26f99896e5
