### ISSUE TITLE
Firedancer genesis blob is not canconical 

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#1519]
**Problem**

When using Agave to deserialize and re-serialize a Firedancer generated GenesisConfig the byte content of the genesis blob changes. 

This causes Firedancer and Agave to disagree about the genesis hash. (Agave uses the canonical one, Firedancer uses the 'raw' hash)

**Comment by ptaffet-jump** [comment]
[agave_genesis.dmp](https://github.com/firedancer-io/firedancer/files/15002267/agave_genesis.dmp)
[fd_genesis.dmp](https://github.com/firedancer-io/firedancer/files/15002272/fd_genesis.dmp)
