### ISSUE TITLE
ballet: add parsers for Solana gossip messages

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#153]
The Solana gossip protocol relies heavily on bincode-fixedint-encoded Serde data structures. 

Those come in the form of peer-to-peer messages and "CRDS" (objects that are gossiped over the network) 

**Tasks**

- Add C data structures
- Add deserializers

There are some more complex parts in the gossip protocol that can be addressed in a second issue (bloom filters, bitset compression)

**Resources**

At the time of writing, 3 implementations of Solana gossip deserializers exist:

- Solana Labs (Rust)
   - CRDS -- https://github.com/solana-labs/solana/blob/676e3e19265ce3f483301f73a4cd8982e02f21c2/gossip/src/crds_value.rs#L84
   - Pull P2P messsages -- https://github.com/solana-labs/solana/blob/676e3e19265ce3f483301f73a4cd8982e02f21c2/gossip/src/crds_gossip_pull.rs#L196
   - Push P2P messages -- https://github.com/solana-labs/solana/blob/master/gossip/src/crds_gossip_push.rs#L55
   - Ping protocol -- https://github.com/solana-labs/solana/blob/master/gossip/src/ping_pong.rs
- Radiance (Go)
   - Generated Go code -- https://pkg.go.dev/go.firedancer.io/radiance@v0.0.0-20230215143431-84c1285873ca/pkg/gossip
   - Serde YAML schema -- https://github.com/firedancer-io/radiance/blob/main/pkg/gossip/schema.yaml
- solana_dissector (Lua) -- https://github.com/terorie/solana_dissector/blob/main/solana.lua

**Comment by smcio** [comment]
I'll be taking this, as per Discord. I've already started working on these, and I've already made quite a lot of progress. I will link up with ameya sometime today.

**Comment by ripatel-fd** [comment]
Done
