### ISSUE TITLE
tango: add io_uring network driver

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#154]
Firedancer currently only supports the AF_XDP network driver which requires a privileged setup.

We should investigate adding an unprivileged network driver for environments where AF_XDP does not make sense.
The choice is between io_uring and epoll with a strong preference for io_uring.

io_uring should use `socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)`.

Requires some changes in the I/O abstraction layer as other parts of the stack expect Ethernet and IP headers, which are not present in regular UDP sockets.

**Comment by lheeger-jump** [comment]
I would not be so quick to dismiss epoll. For small number of sockets, epoll can have comparable performance to io_uring. liburing is a bit cleaner for event loop driven systems

**Comment by smcio** [comment]
@ripatel-jump I'm looking into this one.

**Comment by ripatel-fd** [comment]
Closing as not planned for now. We now have an udpsock network driver. We can reopen this if needed.
