### ISSUE TITLE
quic: add protocol data structures

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#16]
Add C structs for various data structures used in the QUIC protocol

**Comment by ameya-deshmukh** [comment]
Hey @ripatel-jump can take this up with a little bit of guidance from your end. Please let me know if I can start working on it and what you think the approach for this should be.

**Comment by ripatel-fd** [comment]
Thanks @ameya-deshmukh -- My colleague has defined most packet and frame data structures on the `nbridge/quic` branch here: <https://github.com/firedancer-io/firedancer/blob/nbridge/quic/src/net/quic/templ/fd_quic_frames_templ.h>

We're currently in a long review phase of the proposed QUIC changes and always appreciate another pair of eyes over the code we publish. Feel free to drop review comments at <https://github.com/firedancer-io/firedancer/pull/83> or submit PRs against the `nbridge/quic` branch if we missed anything. The team is currently mostly working on security review of this QUIC code through lots of tests, fuzzing, and bounded model checking (cbmc).
