### ISSUE TITLE
Ensure sol_alloc_free is not allowed for new program deployments

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#1673]
Different verification rules are used depending on BPF loader and depending on whether it's a 'deploy' or 'execute' operation. 

Firedancer's BPF loader is missing plumbing to allow different rules though. 
It always allows the same set of syscalls.

sol_alloc_free should be banned for loader v3 deploys but allows for earlier loader executions.

**Comment by ravyu-jump** [comment]
https://github.com/firedancer-io/firedancer/pull/1963 adds a `deploy_checks` flag in the SBPF loader now. Should be trivial to add a check for the `sol_alloc_free` call

**Comment by ravyu-jump** [comment]
Turns out Tom has fixed this 🎉 : https://github.com/firedancer-io/firedancer/pull/2222
