### ISSUE TITLE
Vote program crash-dfdb8301022404adb885053ab38bc3dd79242e8d

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#1720]
Reported by AR.

OOM / out-of-bounds memory access in fd_deque.

https://github.com/firedancer-io/test-vectors/blob/main/instr/fuzz-regtest/crash-dfdb8301022404adb885053ab38bc3dd79242e8d

Relates to #1681

**Comment by ripatel-fd** [comment]
@topointon-jump Is this fixed?

**Comment by ripatel-fd** [comment]
@topointon-jump ping

**Comment by topointon-jump** [comment]
@jumpsiegel mind taking a look? 🙏

**Comment by ripatel-fd** [comment]
No answer in 2 months, closing
