### ISSUE TITLE
flamenco: epoch ctx fixup memory uses dynamic allocation to copy

### ISSUE THREAD

**Issue by arjain4** [firedancer-io/firedancer#1734]
The fixup memory method copies from a dynamic decode. This causes confusion since we have only one case of this and it would be better to just decode without dynamic allocation.

**Comment by ripatel-fd** [comment]
@arjain4 was this fixed?

**Comment by arjain4** [comment]
> @arjain4 was this fixed?

I made some functional fixes to ensure correctness of fixup memory. Have some ideas about doing away with dynamic allocation, will get around to it soon
