### ISSUE TITLE
Switch QUIC ACKs to use a faster algorithm

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#1801]

**Comment by nbridge-jump** [comment]
There is a bit vector stored in the uchar array `stream->tx_ack`.
Each bit in this vector represents the ack status of each byte in the circular buffer `stream->tx_buf`. That is, a bit is '1' iff the corresponding byte in tx_buf has been ack'ed and is no longer required.
Probably the simplest improvement would be to change the type to a ulong array. Then implement branchless versions of the setting and clearing algos. This is likely sufficient
Alternatively, we could track ack ranges, and implement ack range merging and so on. Note that the client can only ack packets, and therefore cannot ack arbitrary bytes of a stream. This means we can link the ack processing with the pkt_meta ranges either logically or directly. This may not be any faster
