### ISSUE TITLE
Update feature timely_vote_credits

### ISSUE THREAD

**Issue by 0x0ece** [firedancer-io/firedancer#1906]
Context: https://github.com/anza-xyz/agave/pull/127

This causes all sort of issues, so left as an independent issue.

We need to support either new genesis and/or new snapshots in order to remake the v118-multi test ledger.

**Comment by ripatel-fd** [comment]
So annoying ...

**Comment by ripatel-fd** [comment]
@jumpsiegel Closing this as completed. AFAIK the test cases were regenerated.
