### ISSUE TITLE
deps: Remove libbpf

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#193]
libbpf is a largely unnecessary dependency.

It contains three major parts:
1. eBPF ELF static object linker and BTF parser
2. bpf(2) wrappers to load eBPF programs into the kernel
3. netlink wrappers to install XDP programs

The ELF object linker is the most complex component. It is required because eBPF bytecode embeds references to BPF map file descriptors which is implemented using static relocations (i.e. the libbpf library applies ELF relocations and loads the resulting code into the kernel). BPF Type Format is entirely optional for AF_XDP.

Parts 2 and 3 can be trivially implemented from scratch.

**Comment by de7215** [comment]
Regarding the linker part, what of the following is required:
- extract linker from libbpf
- use/adopt other linker 
- rewrite the linker

**Comment by ripatel-fd** [comment]
@de7215 The linker should be rewritten to extract the `xdp` section and apply `R_BPF_64_64` relocations. Shouldn't be complicated, maybe 100-200 lines of C. I was planning on working on it next week. (EDIT: BTF and other relocation types are not needed)

**Comment by de7215** [comment]
I could work on this, just specify exact requirements and constraints.

**Comment by ripatel-fd** [comment]
Implemented in https://github.com/firedancer-io/firedancer/commit/dff032871de791e4176960ccfdac0a1fd3d2b3d3
