### ISSUE TITLE
Cursed Nix error in CI

### ISSUE THREAD

**Issue by ripatel-jump** [firedancer-io/firedancer#217]
https://github.com/firedancer-io/firedancer/actions/runs/4484845763/jobs/7885758137#step:3:12141

```
error: filesystem error: cannot rename: Invalid cross-device link [/nix/store/a2pm6g5dp50risrwc48jgi0dibwmg0k8-quictls-3.0.8+quic.drv.chroot/nix/store/b4by3i18nkb5ybjwjcx8r2x5jvmcngds-quictls-3.0.8+quic] [/nix/store/b4by3i18nkb5ybjwjcx8r2x5jvmcngds-quictls-3.0.8+quic]
```

@marcus-jump pls fix 🥺

**Comment by ripatel-fd** [comment]
Looks like this is related due to mixing of a Nix cache mount and the main Nix store. One potential solution is to register the pre-baked cache as a separate "remote" and copy instead of hardlinking. 

Alternatively, we can just update the Nix cache with a pre-baked quictls rebuild.

**Comment by marcus-ares** [comment]
I rebuilt the image. Packer was less than cooperative with the huge ar line outputted when building openssl.
