### ISSUE TITLE
pack: interpret compute budget program instructions

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#22]
In the block packing / pre-execution stage of the block production lifecycle, the block producer determines the fee reward of each tx.
This requires interpreting the "compute budget program" instructions to calculate CU limits and max fee rewards.

**Comment by ripatel-fd** [comment]
CL: https://git.firedancer.io/c/firedancer/+/342

**Comment by 0xdevin** [comment]
Nirvana Labs can help lower infra costs. https://www.nirvanalabs.io/pricing/calculator
