### ISSUE TITLE
Risk of Sign-Tile Exhaustion

### ISSUE THREAD

**Issue by 0x0ece** [firedancer-io/firedancer#2350]
### Tracking: 
ND:4

## Summary
Using a single sign tile for all crypto operations increases the risk of a validator DoS, e.g. if the sign tile is exhausted by a QUIC DoS.

Commit: 30fb51e2634d8ca80de34e497169bf8a0f6183a7 (quic - fixed RETRY)

## Details
By design, there is only one sign tile per server. This single sing tile handles QUIC certificate signing, as well as all other keyguard operations.

In the worst case an resource exhaustion attack on the quic tile can bring down the signer tile and with it all other operations needed for the validator to run.

Depending on the exact commit, and if retry is enabled, we've seen different amount of possible sign-tile utilization, the newest version tested had ~20% sign utilization with a single quic tile doing 100% new connection handling. But the exact percentages could be 'optimized' and depend on the hardware.

We currently estimate that it would be possible to exhaust the sign tile with around 3-4 QUIC tiles, but haven't tested that yet.

## Suggested fixes
To increase resiliency, we recommend using a dedicated quic-sign tile only responsible for the quic certificate signing operations. It is fairly easy to reach externally, and has the possiblity to stall later tiles on their signing operations.

Another aproach might be to introduce a priority queue to the sign tile, so 'validator-triggered' sign operations are always handled first.

**Comment by mmcgee-jump** [comment]
Not valid finding, the sign tile polls different ins in a round robin fashion so no producer can cause exhaustion.
