### ISSUE TITLE
TLS: potential FD_TEST failure due to transport parameter size mismatch

### ISSUE THREAD

**Issue by 0x0ece** [firedancer-io/firedancer#2351]
In the fd_quic_tls_hs_new function of src/waltz/quic/tls/fd_quic_tls.c there is an FD_TEST on the transport_params_raw_sz:

`FD_TEST( transport_params_raw_sz <= sizeof(self->self_transport_params) );`

Note that self_transport_params has a size of 255. However it appears that certain callers of fd_quic_tls_hs_new (such as fd_quic_handle_v1_initial) will allow a raw transport parameter size of up to FD_QUIC_TRANSPORT_PARAMS_RAW_SZ, which is 1200. There's some influence on transport parameters from remote connections, but it hasn't been confirmed if that this would be enough to push over the 255 byte mark.

The FD_TEST macro calls FD_LOG_ERR if the check fails, which would result in system termination.

**Comment by kbowers-jump** [comment]
Generally, FD_TEST is meant for unit testers.  Production code in general should avoid using FD_TEST (with maybe an exception where the correct handling is to "die on site" ... though FD_LOG_CRIT would arguably be better there because then you can get a core dump when the situation happened for post mortem analysis).

**Comment by ripatel-fd** [comment]
The code path in question was unreachable. When the server's own transport parameters grow beyond bounds then that FD_TEST crashes the validator. However, the structure of the server's transport parameters is hardcoded and cannot be influenced from outside. It's good defense in depth to gracefully handle this case anyways. I'm working on a patch.
