### ISSUE TITLE
ballet: add SHA-384

### ISSUE THREAD

**Issue by ripatel-jump** [firedancer-io/firedancer#242]
Another hash function.

SHA-384 is a modified SHA-512. It has a different input state and the output is truncated to 48 bits.

Required for QUIC, which uses a HKDF over HMAC-SHA384 for the TLS_AES_256_GCM_SHA384 ciphersuite.

**Comment by ripatel-fd** [comment]
Implemented in 
- https://github.com/firedancer-io/firedancer/commit/e2859fa78de46a0435311e6d7535b05e7191094e
- https://github.com/firedancer-io/firedancer/commit/3232dc566e67db9335e62ea3a22718d2deeced54
- https://github.com/firedancer-io/firedancer/commit/affbea093b650397457458e4c08e1f7e365902e9
