### ISSUE TITLE
ARP support for XDP

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#259]
Most real-world deployments will require a userland ARP table and lookup mechanism for TX requests.

Add ARP logic and hook up into fd_xdp.

**Comment by llamb-jump** [comment]
Does the handling of ARP traffic need to be performant? Could we pass all ARP traffic to the kernel?

**Comment by ripatel-fd** [comment]
@llamb-jump Yeah, we could pass ARP traffic to the kernel and then mirror the kernel's routing / neighbor tables.
