### ISSUE TITLE
quic: remove OpenSSL RAND

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#265]
fd_quic uses the OpenSSL RAND API to derive connection IDs. (Low prio)
This should be replaced with an in-house RNG, preferably cryptographically secure. The consequences of using a predictable RNG for connection IDs (such as fd_rng) is not well known. Presumably, the impact is low considering connection IDs in QUIC are optional. 

As always, the motivation for removing deps on OpenSSL is to reduce code footprint, improve performance, and improve portability (for targets that cannot run OpenSSL)

**Comment by AlberErre** [comment]
Hey @ripatel-jump! I would love to work on this in-house RNG cryptography module.

Could you assign me the issue? 👀

Also, I would need to know the target branch to work with, as looks like fd_quic features are under active development 🚀

**Comment by ripatel-fd** [comment]
@AlberErre Please feel free to fork off `milestone-1.1-demo`. Though I'm not sure we are ready to accept contributions to the cryptography parts of QUIC at the moment (@nbridge-jump maintains this part). Other parts in the Solana protocol have a ChaChaRNG CSPRNG. However, we haven't ported it to Firedancer yet. I suggest once it's available, we use ChaChaRNG instead of fd_rng to avoid security issues introduced by weak RNG.

We would love to accept contributions adding ChaCha20Core as the team currently doesn't have enough bandwidth to take this issue: https://github.com/firedancer-io/firedancer/issues/151

**Comment by AlberErre** [comment]
Perfect @ripatel-jump, makes sense to use the same implementation as other parts of solana. 

Ok! I'm happy to work on #151, you can assign me that issue then 🚀

**Comment by ripatel-fd** [comment]
@nbridge-jump @marcus-jump The Solana ChaCha20Rng is now merged, but it's not a CSPRNG, just deterministic and IID rand, as it hardcodes the nonce to zero (violates nonce reuse recommendations). We can probably modify turn it into a real CSPRNG if we eliminate nonce reuse, but it needs further research.

**Comment by ripatel-fd** [comment]
@mmcgee-jump @marcus-ares What are your thoughts on this? This is labelled as high priority, but I suspect this is no longer the case.

**Comment by mmcgee-jump** [comment]
:shrug: Be nice to remove OpenSSL but it's there for now. We probably have higher priorities than removing the `getpid()` / `getrandom()` calls for now.

**Comment by ripatel-fd** [comment]
fd_quic no longer uses OpenSSL RAND.
