### ISSUE TITLE
quic: improve event queue complexity

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#266]
Reschedule and abort of queued service events is currently O(n) where n is number of connections. 
At the moment, fd_quic is unsuitable to serve high numbers of connections.
Affected parts of the code should adopt sublinear complexity algorithms instead. (e.g. red-black tree instead of ring would be more suitable for queue)

**Comment by nbridge-jump** [comment]
Intent is to add a reverse reference to the priority queue, which will make reschedule O(lg N) too. This will be more performant than R/B tree

**Comment by ripatel-fd** [comment]
Done in https://github.com/firedancer-io/firedancer/pull/3250
