### ISSUE TITLE
Support external AF_XDP setup

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#289]
Currently, the fd_frank_quic tile sets up an AF_XDP socket on join, which requires capabilities. 

Firedancer might not have the required permissions in some environment. We should support a mechanism to set up AF_XDP in advance and migrate over the file descriptors between processes (AF_UNIX).

**Comment by ripatel-fd** [comment]
cc @leoluk

**Comment by ripatel-fd** [comment]
Probably best to use the API of Intel's AF_XDP plugin https://github.com/intel/afxdp-plugins-for-kubernetes/ (Apache-2.0 licensed)

[Architecture Diagram](https://github.com/intel/afxdp-plugins-for-kubernetes/blob/main/docs/high_level_arch.png); [Sequence Diagram](https://github.com/intel/afxdp-plugins-for-kubernetes/blob/main/docs/sequence.png); [Server-side code](https://github.com/intel/afxdp-plugins-for-kubernetes/blob/main/internal/udsserver/udsserver.go)

**Comment by ripatel-fd** [comment]
The tooling for this is going to live outside of the Firedancer repo, so I'm going to close this as not planned.

**Comment by leoluk** [comment]
It'll still require work on the Firedancer side to implement the client side of the protocol
