### ISSUE TITLE
Incorrect enforcing of the disable_status_cache config option on a testnet config

### ISSUE THREAD

**Issue by vkomenda** [firedancer-io/firedancer#3079]
Tag v0.114.20013.

Initial configuration using the provided testnet.toml fails due to fdctl assigning an incorrect value to a development option.

```
$ sudo ./build/native/gcc/bin/fdctl configure init all --config src/app/fdctl/config/testnet.toml 
ERR     10-09 18:15:51.605871 196690 f0   0    src/app/fdctl/config.c(659): trying to join a live cluster, but configuration enables [development.bench.disable_status_cache] which is a development only feature
```

Even more interesting, while initialisation with `src/app/fdctl/config/default.toml` succeeds, adding the testnet values to that TOML file leads to the same error message above. This is given that it is clearly stated `disable_status_cache = false`.

Something is not right in how devnet options are interpreted and this happens as a side effect of using testnet values. Missing unit tests maybe ;)

**Comment by ptaffet-jump** [comment]
This is fixed in v0.115.20013. Apologies for the issue!
