### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#37]
**Problem**

The workspace / tile system uses various Linux-only APIs. Because of this, Firedancer fails to build on macOS.
There are lots of macOS developers who might want to use Firedancer APIs, or even run a macOS validator (although that is not recommended)

**Suggested fix**

However, the Darwin kernel offers replacements for most of these APIs (e.g. CPU pinning and huge pages).
They are just largely undocumented and annoying to work with.

**Comment by shuimuliang** [comment]
do u need Rust/Solana engineer?
i'm open for Solana project.

**Comment by smcio** [comment]
I can implement macOS support, if you're open to community contributions at this time?

**Comment by ripatel-fd** [comment]
@smcio Thanks, we'd love to merge a contribution for macOS support.

Ideally, changes would be submitted to https://git.firedancer.io but a GitHub PR is fine too.

**Comment by smcio** [comment]
Good stuff - I'll get working on it. Thanks.

**Comment by ripatel-fd** [comment]
@smcio FYI, the NUMA interface is slightly changing: https://git.firedancer.io/c/firedancer/+/413
I also added some stubs for fixing NUMA support on macOS, but haven't tested if that compiles.
Hope that simplifies the integration.

**Comment by smcio** [comment]
Hey @ripatel-jump - should hopefully done with this either today or tomorrow.

**Comment by ripatel-fd** [comment]
Thanks a lot! Also, if you have any questions, you can reach us via the GitHub Discussions tab or via e-mail.

**Comment by smcio** [comment]
Hi @ripatel-jump , I've made the changes necessary to get firedancer built on macOS, including replacing use of Linux APIs with Darwin equivalents, and I'd like to get it running to see whether it's working properly. 

It'd be great to ask a few questions to you and the team. I can't see a "Discussions" tab in my GitHub interface unfortunately. Does the team perhaps have a Discord? I can see a channel for Firedancer on the Solana discord server, but I didn't see much recent activity in there and of course I wouldn't have the right permissions to write in there.

**Comment by CantelopePeel** [comment]
If you could share a Discord handle we can add you. Or message me at CantelopePeel#0343.

**Comment by CantelopePeel** [comment]
_but_ @ripatel-jump would you kindly enable the discussions tab?

**Comment by ripatel-fd** [comment]
> Hi @ripatel-jump , I've made the changes necessary to get firedancer built on macOS, including replacing use of Linux APIs with Darwin equivalents, and I'd like to get it running to see whether it's working properly.

@smcio That's great news. For testing, there are some concurrency test scripts in the `./build/linux/gcc/x86_64/unit-test/` dir such as `test_ipc_full`. If those pass, the integration can be considered functional. 

> It'd be great to ask a few questions to you and the team. I can't see a "Discussions" tab in my GitHub interface unfortunately. 

> but @ripatel-jump would you kindly enable the discussions tab?

@smcio @CantelopePeel  Yes, sorry, I thought that had already been enabled. But turns out I had to click another green button to open that up.

> Does the team perhaps have a Discord? I can see a channel for Firedancer on the Solana discord server, but I didn't see much recent activity in there and of course I wouldn't have the right permissions to write in there.

@smcio Yes, we have a developer Discord and would love to invite you there.
This Discord is invite-only for now mostly because of lack of moderation but we can send you an invite link privately.

Could you push up a draft PR with your changes? I'll email it to the Git email associated with the commit. Thank you.

**Comment by ripatel-fd** [comment]
There is now a machine target for macOS: https://github.com/firedancer-io/firedancer/blob/main/config/machine/macos_clang_m1.mk
It currently provides a non-hosted environment (meaning code can compile but file system and shared memory is not available).

**Comment by sgulinski** [comment]
@ripatel-fd What's the status of macOS support? I noticed there's a machine target for macOS, but I still see some Linux-only APIs being used.

**Comment by riptl** [comment]
@sgulinski macOS support is not planned. We try to ensure periodically that parts of the project at least compile on macOS. As you noted, the sandbox and usages of system APIs are incompatible with macOS. Proper shared memory support with huge pages would require interfacing with undocumented darwin-xnu APIs.
