### ISSUE TITLE
Investigate and hopefully remove `sendto` syscall from QUIC tiles

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#674]
When binding the XSK to queue on network interface, we set

```C
sxdp_flags    = XDP_USE_NEED_WAKEUP | (ushort)xsk->params.zerocopy
```

`XDP_USE_NEED_WAKEUP` triggers a mode where we need to call `sendto(2)` to have the kernel / driver service the queues. It does not feel like this should be necessary. The syscall is a performance and security hit, and the non `NEED_WAKEUP` option should have the driver take a core and spin, constantly servicing the queue without either of these issues.

**Comment by nbridge-jump** [comment]
Given the variety of drivers out there, I don't think we should consider removing XDP_USE_NEED_WAKEUP. It was added to improve performance

**Comment by ripatel-fd** [comment]
@mmcgee-jump Can we close this? Or rewrite this issue to restrict the file descriptors that are allowed with sendto?

**Comment by mmcgee-jump** [comment]
There's another issue for the file descriptor restriction, but I don't want to close this until we understand why we need to call `sendto` at all. I have not heard a good explanation for this and haven't had time to dig into the driver code myself yet.

**Comment by ripatel-fd** [comment]
@mmcgee-jump Its use is recommended by the Linux kernel docs, and we've seen performance regressions not using it. How is that not a good explanation?
