### ISSUE TITLE
Implement simple HTTP server tile with diagnostics

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#691]
Little HTTP server. Would serve prometheus metrics, diagnostics, and possibly a cute live view like the monitor command does in a terminal.

**Comment by ripatel-fd** [comment]
I'm a big fan of this library for parsing HTTP requests: https://github.com/h2o/picohttpparser/blob/master/picohttpparser.c

Serving responses is trivially done via printf.
