### ISSUE TITLE
bazel: add rules_fuzzing

### ISSUE THREAD

**Issue by terorie** [firedancer-io/firedancer#7]
**Feature Request**

Firedancer will rely heavily on fuzzing to ensure code correctness beyond unit tests.

The build system should support compilation with fuzz-instrumentation and linkage with libFuzzer/AFL/etc.

Ideally, we can also integrate Firedancer with the famous OSS-Fuzz to maintain corpora over time and periodically re-run tests, but that's a separate issue.

**Suggested Fix**

- Pull in Bazel's rules_fuzzing https://github.com/bazelbuild/rules_fuzzing
- Add an example test to illustrate how to write fuzz targets (e.g. pcap parser)
- Documentation

**Comment by ripatel-fd** [comment]
https://git.firedancer.io/c/firedancer/+/118
