### ISSUE TITLE
Features for pack

### ISSUE THREAD

**Issue by ptaffet-jump** [firedancer-io/firedancer#704]
- [x] Prevent writelocking of sysvars
- [x] Blockhash-based expiry (or just a conservative time-based version)
- [ ] Reject any transaction with duplicate accounts
- [ ] Address lookup tables
- [x] Fast bitset optimization
- [ ] `tx_account_lock_limit`
- [ ] Dedup gossiped votes

**Comment by ptaffet-jump** [comment]
The path from bank back to pack may no longer be necessary

**Comment by mmcgee-jump** [comment]
Split into separate issues
