### ISSUE TITLE
Curve25519 multi-scalar multiplication

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#782]
The Solana ZK Token Proof program and new VM features introduce multi-scalar multiplication operations on top of Curve25519 groups (Ed25519 and ristretto255).

**Comment by ripatel-fd** [comment]
Some thoughts from recent discussion with @kbowers-jump regarding batch processing:

- Consider introducing a streaming-style API for MSM inputs (such that point decompression can be interleaved with MSM calculations)
- Each scalar multiplication has decent ILP, so batching is not high priority
- Possible vartime optimizations involve changing up control flow depending on scalar bit patterns

**Comment by 0x0ece** [comment]
MSM is implemented.
