### ISSUE TITLE
README: What is Firedancer?

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#79]
Our current README jumps straight into technical configuration of the host.

We should probably add a brief summary of this project to Firedancer & development status & not-prod-ready disclaimer

**Comment by hydrogenbond007** [comment]
Wanna assign this to me, made some notes on fd in my logseq might be useful here

**Comment by abebeos** [comment]
> We should probably add a brief summary of this project to Firedancer & development status & not-prod-ready disclaimer

Yes, though you should keep the "product summary" very minimal, see additionally https://github.com/firedancer-io/firedancer/pull/202#issuecomment-1528902735

**Comment by ripatel-fd** [comment]
Completed in https://github.com/firedancer-io/firedancer/pull/441
