### ISSUE TITLE
quic: maybe remove `tx_buf_size` from config

### ISSUE THREAD

**Issue by mmcgee-jump** [firedancer-io/firedancer#827]
default.toml has a `tx_buf_size` like

```toml
# TODO: This should be removed.  We never transmit stream data
# so this should be unused.
tx_buf_size = 4096
```

Verify that this is unneeded and remove it + the plumbing.

**Comment by mmcgee-jump** [comment]
Looks like this is used, the comment needs to be fixed, and the buffer size should probably not be configurable, just fixed at 4096.

**Comment by ripatel-fd** [comment]
@mmcgee-jump This is unused. tx_buf_size is the tx_buf_sz argument of fd_quic_stream. The transmit buffer is only used when making server-to-client unidirectional or bidirectional streams. Neither of which is currently happening.
