### ISSUE TITLE
bzip2 fails to link sometimes 

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#854]
The bzip2 crate, which Solana Labs imports, arbitrarily provides bzip2 (or not) depending on system pkg-config.
Firedancer, however, does not respect pkg-config and never provides bzip2, even when the crate does not.

https://github.com/alexcrichton/bzip2-rs/blob/3032f3790742bffda521e54d14429f459e078eba/bzip2-sys/build.rs#L16-L23

Third parties have run into this issue too. Therefore, it should be fixed before a public release.

Suggested fix: https://github.com/firedancer-io/solana/pull/15

**Comment by brooksprumo** [comment]
The Labs client no longer allowed using bzip2 for snapshot archival. It may not be necessary for Firedancer to support this.

**Comment by ripatel-fd** [comment]
@brooksprumo The master branch of Labs still imports bzip2 in 5 crates. The rocksdb crate has an additional bug on master where it depends on bzip2-sys even though the Labs code suggests that bzip2 in RocksDB is specifically disabled*.

**Comment by brooksprumo** [comment]
> @brooksprumo The master branch of Labs still imports bzip2 in 5 crates.

Gotcha. Yeah, for snapshots specifically we'll likely support loading bzip2 for a while, even if we don't allow bzip2 for new archives. (Mostly for historic replay, I would imagine.)

**Comment by mmcgee-jump** [comment]
Fixed on our solana. branch
