### ISSUE TITLE
Large pages initialization only for a single NUMA node

### ISSUE THREAD

**Issue by Jefferson111** [firedancer-io/firedancer#940]
I was casually reading the codebase and it seems like the large page initialization are hard coded only for the 1st numa node `node0`.

https://github.com/firedancer-io/firedancer/blob/7b284c8238404d7c88e5a0f565d080c13314896a/src/app/fdctl/configure/large_pages.c#L54

I was kind of expecting a shared limit to be used with something: `/sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages` or configuring the large pages for all the numa nodes `/sys/devices/system/node/node*/hugepages/hugepages-1048576kB/nr_hugepages`.

I am trying to understand what's the rationale of doing this? I suspect that there is some page migration going on subsequently, like in [shmem](https://github.com/firedancer-io/firedancer/blob/01888afa6a0e3503ae9f12a0b2c5efcf4b64a4ad/src/util/shmem/fd_shmem_admin.c#L233), but I also read that page migration across numa nodes might result in demotion of the page size. Would be great if someone can shed more light on what's going on? Thanks!

**Comment by mmcgee-jump** [comment]
It's a good observation, and you aren't missing anything! We just haven't done the work to allocate memory in the right places yet.
