### ISSUE TITLE
util/log: hex dump routine

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#95]
**Problem**

Hex dumping an arbitrary-sized blob is a fairly common operation.

But at the moment, we only have a helper macro for `printf`-style formatting of 16-byte chunks: `FD_LOG_HEX16_FMT`.

**Suggested Fix**

Introduce an API for writing `hexdump` / `xxd` style dumps to fd_util log.

**Comment by smcio** [comment]
I can take this one. I'll put up a PR for this shortly.

(I'm assuming a community contribution is OK given the 'good first issue' label 🙂 )

**Comment by ripatel-fd** [comment]
Closing this issue since this has been implemented. Thanks a lot for this very useful contribution, @smcio!
