### ISSUE TITLE
Non-x86 support

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#99]
**Problem**

Tango is incompatible with other architectures like armv8, RISC-V, Power9.

Most of Firedancer's assumptions about the target platform are compatible with the above architectures.

However, Tango currently depends on the fact that in x86 writes from one CPU don't get reordered when observed from another CPU.
Thus, the code only uses compiler fences to prevent writes from being reordered at compile-time.

Common RISC architectures do not provide such guarantees.

**Suggested Fix**

- add write memory barriers when writing into critical sections
- add data dependency barriers before and after reading sequence numbers from critical sections

**Comment by mmcgee-jump** [comment]
Not currently planned, will revisit when needed
