### ISSUE TITLE
Add fuzz_sbpf_loader2_diff to ClusterFuzz

### ISSUE THREAD

**Issue by ripatel-fd** [firedancer-io/firedancer#998]
fuzz_sbpf_loader2_diff is a fuzzer built with Rust FFI. It is currently not included in the ClusterFuzz configuration.

**Comment by ripatel-fd** [comment]
@marctrem Could you take a look at this?

**Comment by ripatel-fd** [comment]
Chatted with @marctrem -- Since `fuzz_sbpf_loader2_diff` is built using cargo, it is currently not built by CI.

Options include
1. Adding it to CI 
2. Separating it out into another repo (This is an ongoing project with Solana Labs)
3. Allow ClsuterFuzz to pick up binaries from a separate location in object storage. Then manually upload the targets

**Comment by marctrem** [comment]
> You need the latest Rust stable, then:
> cd ffi/rust/firedancer-diff/fuzz
> then cargo build --release

-- @ripatel-fd
